# Generated by Django 4.0.4 on 2022-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='post',
            name='countB',
            field=models.IntegerField(null='True'),
        ),
    ]
